### ISSUE TITLE
巨型熔炉核心自动搭建

### ISSUE THREAD

**Issue by Windows2066** [FalAut/Mierno#2]
### Modpack Version

v0.0.5

### Describe the bug

![image](https://github.com/user-attachments/assets/1c0b517a-231c-4aed-a9ef-294e2d8f049f)

巨型熔炉核心在搭建时玩家所在位置不会搭建，但是扣除了所有的巨型熔炉框架

**Comment by FalAut** [comment]
感谢你的报告，已在开发中修复
