### ISSUE TITLE
配方缺失

### ISSUE THREAD

**Issue by Windows2066** [FalAut/Mierno#4]
### Modpack Version

v0.0.5

### Describe the bug

钢锭和钢块的配方缺失

**Comment by FalAut** [comment]
用物质聚合器做钢粒

**Comment by FalAut** [comment]
![image](https://github.com/user-attachments/assets/2ae6f138-911f-486e-8165-92c7e89100b9)
![image](https://github.com/user-attachments/assets/730a1035-368f-4a9e-a25b-0f255cc92a27)

**Comment by Windows2066** [comment]
![image](https://github.com/user-attachments/assets/b6b6dadf-82a5-4c16-923f-f60abe2965b0)

**Comment by FalAut** [comment]
啊

**Comment by FalAut** [comment]
已在开发中修复，感谢你的报告
